## fill information by env file
dbt_movies:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: admin
      pass: admin123
      dbname: love_movies
      schema: analytics


  target: dev
